---
title: "outer measure on R"
output: github_document
---

$$
\newcommand\R{\mathbf R}
$$

# Outer Measure on $\R$

## 启发性讨论

Goal

-   To extend integration to a larger class of functions

-   mainly **the domain of a function as the union of subsets**

    -   assign a size to each of those subsets

::: def
The length $\ell(I)$ of an open interval $I$ is defined by $$
\ell(I)= \begin{cases}b-a & \text { if } I=(a, b) \text { for some } a, b \in \mathbf{R} \text { with } a<b, \\ 0 & \text { if } I=\varnothing, \\ \infty & \text { if } I=(-\infty, a) \text { or } I=(a, \infty) \text { for some } a \in \mathbf{R}, \\ \infty & \text { if } I=(-\infty, \infty) .\end{cases}
$$
:::

We have $A \subseteq \mathbf{R}$, then the size of $A$ shall at most the sum of len of a sequence of open intervals whose union contains $A$. (包含关系的集合之和不能比原来的集合的长度还要大)

::: def
The outer measure $|A|$ of a set $A \subseteq \mathbf{R}$ is defined by $|A|=\inf \left\{\sum_{k=1}^{\infty} \ell\left(I_k\right): I_1, I_2, \ldots\right.$ are open intervals such that $\left.A \subseteq \bigcup_{k=1}^{\infty} I_k\right\}$.
:::

::: eg
有限集合的外测度为0.

Suppose $A=\left\{a_1, \ldots, a_n\right\}$ is a finite set of real numbers. Suppose $\varepsilon>0$. Define a sequence $I_1, I_2, \ldots$ of open intervals by $$
I_k= \begin{cases}\left(a_k-\varepsilon, a_k+\varepsilon\right) & \text { if } k \leq n, \\ \varnothing & \text { if } k>n .\end{cases}
$$

Then $I_1, I_2, \ldots$ is a sequence of open intervals whose union contains $A$. Clearly $\sum_{k=1}^{\infty} \ell\left(I_k\right)=2 \varepsilon n$. Hence $|A| \leq 2 \varepsilon n$. Because $\varepsilon$ is an arbitrary positive number, this implies that $|A|=0$.
:::

## 外测度的好性质

::: prop
可数集合的测度为0

Every countable subset of $\mathbf{R}$ has outer measure 0 .
:::

对于 $A=\left\{a_1, a_2, \ldots\right\}$ 只要选取$I_k=\left(a_k-\frac{\varepsilon}{2^k}, a_k+\frac{\varepsilon}{2^k}\right)$就好了.

::: prop
外测度保序

Suppose $A$ and $B$ are subsets of $\mathbf{R}$ with $A \subseteq B$. Then $|A| \leq|B|$.
:::

假设$I_1, I_2, \ldots$ 是开区间, 他们的并包含了B, 那么他们的并一定包含了A. 于是$|A| \leq \sum_{k=1}^{\infty} \ell\left(I_k\right)$. 取下极限就有了.

::: def
平移变换(translation)

If $t \in \mathbf{R}$ and $A \subseteq \mathbf{R}$, then the translation $t+A$ is defined by $$
t+A=\{t+a: a \in A\} .
$$
:::

::: prop
外侧度平移不变

Suppose $t \in \mathbf{R}$ and $A \subseteq \mathbf{R}$. Then $|t+A|=|A|$.
:::

这是因为 $\ell$ 两个东西减过之后就会是0. $|t+A| \leq \sum_{k=1}^{\infty} \ell\left(t+I_k\right)=\sum_{k=1}^{\infty} \ell\left(I_k\right)$

::: prop
可数可加性

Suppose $A_1, A_2, \ldots$ is a sequence of subsets of $\mathbf{R}$. Then $$
\left|\bigcup_{k=1}^{\infty} A_k\right| \leq \sum_{k=1}^{\infty}\left|A_k\right| .
$$
:::

::: prf
-   If $\left|A_k\right|=\infty$ for some $k \in \mathbf{Z}^{+}$, apparently
-   $\varepsilon>0$. For each $k \in \mathbf{Z}^{+}$, let $I_{1, k}, I_{2, k}, \ldots$ be a sequence of open int. contains $A_k$ s.t. $\sum_{j=1}^{\infty} \ell\left(I_{j, k}\right) \leq \frac{\varepsilon}{2^k}+\left|A_k\right|$.
    -   thus $\sum_{k=1}^{\infty} \sum_{j=1}^{\infty} \ell\left(I_{j, k}\right) \leq \varepsilon+\sum_{k=1}^{\infty}\left|A_k\right|$.
    -   
:::
