---
title: "实验1:从U盘启动Linux"
author: "gwzhang"
date: "`r Sys.Date()`"
output: github_document
---

## 按下电源键之后

你是否留意过, 在按下电源键之后, 电脑需要一段时间才可以启动完成. 那么, 在这一会儿过程中, 到底发生了什么? 这个实验的过程中, 我们会简单介绍. 最后, 我们会带领大家做一个可以直接从USB启动的系统.

理解机械的计算机世界, 很多时候可以采用类比的方法. 实际上, 这些系统在某些大的原则和设计上和人类世界很相似. 如果你还没有对它有最基本的印象, 可以参考[《开天辟地: 电脑急救与安装篇》的第一节(bilibili P3)](https://www.bilibili.com/video/BV1et411y7cH?p=3). 作为复习,

-   电脑有输入(如键盘, 鼠标)和输出设备(如屏幕), 可以与外界交互.
-   CPU是电脑的 "大脑".
-   在电脑运行过程中, CPU只能操作内存中的数据. 通常程序的数据会保存在内存中. 内存存储速度非常快, 远远超过硬盘. 但是在没有电的时候内存中的数据会全部消失.

如果类比做一个人的日常的话, 人的输入是五官感受到的, 输出是嘴巴说出来、行动做出来的. 但是更恰当的描述是, 这人每天早上起来就会忘记自己记住的所有的东西. 为了弥补这一点, 他有一本《每天早上醒来请读这个》的笔记. 于是在醒来之后他会阅读这个文档, 来完成一些基础的认知操作, 并且在一天中把有趣的事情记录下来. 这样后面就可以知道发生了什么了.

::: gossip
这里直接偷了**白石定規**对于《魔女の旅々》第四卷[**艾姆妮西亚**](https://zh.moegirl.org.cn/%E8%89%BE%E5%A7%86%E5%A6%AE%E8%A5%BF%E4%BA%9A "艾姆妮西亚")(アムネシア)的设定. 有时候会发现有些艺术创作还是可以取材于实际生活的更加抽象的部分的.
:::

我们本次主要做的事情是看一看《每天早上醒来请读这个》写了什么. 对于一个人来讲, 这需要首先知道一些基本信息, 然后搞明白自己接下来要干什么. 比如, 把这份笔记通读一遍, 然后按照"对目标的要求"继续行事.

在计算机的世界里面, 这《每天早上醒来请读这个》有一个专门的名字, 通常叫做"固件(firmware)". 这是因为早些时候, 这一小段指令会写死在这本书(一个特定的芯片)里面, 不能修改. 如果想要升级必须要换芯片. 固件的功能大体上来说有两个

-   我是谁? 我在哪? (运行程序前进行计算机系统配置): CPU电压 ...

-   接下来该干啥? (不严格地说, 加载操作系统)

第一个主要部分现在还太过琐碎. 这个实验里面我们主要来看第二个.

```{python}
for i in range(10):
  print(i)
```
